version: "2.1"

services:
  zoo1:
    command: "-persist"
  zoo2:
    command: "-persist"
  zoo3:
    command: "-persist"
  namenode:
    command: "/start-namenode.sh -persist"
  master:
    command: "master -persist"
