server:
  context-path: /${spring.application.name}
  port: 8443
  non-secure-port: 8080
  ssl:
    client-auth: WANT
    trust-store: 'classpath:/testCA.p12'
    trust-store-type: PKCS12
    trust-store-password: 'ChangeIt'
    key-store: 'classpath:/testServer.p12'
    key-store-type: PKCS12
    key-store-password: 'ChangeIt'

management:
  context-path: /mgmt
  security:
    roles: Administrator,JBossAdministrator

endpoints:
  health:
    sensitive: false

security:
  sessions: STATELESS
  enable-csrf: false
  user.password: passwordNotUsed
  jwt.ttl: 86400
  issuers-required: true
  enforce-allowed-callers: false

spring:
  # Enable service discovery using Consul
  cloud:
    discovery:
      enabled: true
    consul:
      enabled: true
      host: discovery
      discovery:
        port: ${server.non-secure-port}
        health-check-path: ${server.context-path}${management.context-path}/health
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      # Allow a long time for the Consul agent to become available.
      retry:
        max-attempts: 120
  # Use discovery to find the RabbitMQ server
  rabbitmq:
    discovery:
      enabled: true
      failFast: true
