spring:
  cloud:
    stream:
      rabbit:
        bindings:
          auditSource:
            producer:
              republishToDlq: true
          logAuditSink:
            consumer:
              autoBindDlq: true
          accumuloAuditSink:
            consumer:
              autoBindDlq: true
      bindings:
        auditSource:
          destination: 'audit'
        logAuditSink:
          destination: 'audit'
          group: 'log'
        accumuloAuditSink:
          destination: 'audit'
          group: 'accumulo'

audit:
  log:
    enabled: true
  accumulo:
    enabled: false

logging:
  level:
    datawave.microservice.audit: DEBUG