server:
  ssl:
    client-auth: NEED

spring:
  security:
    datawave:
      use-trusted-subject-headers: true

mock:
  users:
    # Defines a regex such that, if the incoming subject DN matches the regex, the user is considered to be a server UserType
    server-DN-regex: .*server.*
    # Define roles (and the associated Accumulo auths) that are applied to all incoming users unless the name is found in the per-user map
    global-roles-to-auths:
      AuthorizedUser: AUTH_USER
      JBossAdministrator: JBOSS_ADMIN
    # Define per-user roles and auths. If the incoming DN (in lower-case subjectDN<issuerDN> form) matches an entry here, the
    # corresponding roles and authorizations are provided instead of the global ones.
    #per-user-roles-to-auths:
    #  "subjectDN<issuerDN>":
    #    ROLE1: auth1
    #    ROLE2: auth2
    #    ROLE3: auth3

logging:
  level:
    datawave.microservice.authorization: DEBUG