server:
  port: 8080
  ssl:
    enabled: false

security:
  jwt:
    enabled: false

management:
  security:
    enabled: false

hazelcast:
  server:
    initialMergeDelaySeconds: 50
    xml-config: |
                <hazelcast xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                            xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-3.9.xsd"
                            xmlns="http://www.hazelcast.com/schema/config">
                  <!-- The datawaveUsers cache is used by the authorization service -->
                  <map name="datawaveUsers">
                    <backup-count>1</backup-count>
                    <time-to-live-seconds>86400</time-to-live-seconds>
                    <eviction-policy>LFU</eviction-policy>
                    <max-size policy="USED_HEAP_SIZE">50</max-size>
                  </map>
                </hazelcast>

spring:
  cloud:
    consul:
      discovery:
        port: ${server.port}
        tags:
          hzPort=${hazelcast.cluster.port}, hzHost=${hazelcast.cluster.host}
