spring:
  security:
    datawave:
      jwt:
        enabled: false

hazelcast:
  server:
    # How long to wait (in seconds) before performing the first split-brain merge. When a number
    # of cache servers start up at once, they will form individual clusters because the attempt
    # to create a cluster happens before the server has registered in Consul. Therefore, the split
    # brain merge will take care of joining the multiple clusters.
    initialMergeDelaySeconds: 50
    xml-config: |
                <hazelcast xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                            xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-3.9.xsd"
                            xmlns="http://www.hazelcast.com/schema/config">
                  <!-- The datawaveUsers cache is used by the authorization service -->
                  <map name="datawaveUsers">
                    <!-- Keep 2 backup copies of data (so we have 3 copies total) -->
                    <backup-count>2</backup-count>
                    <!-- No matter what, entries get evicted after this time. -->
                    <time-to-live-seconds>86400</time-to-live-seconds>
                    <!-- Allow 2GB for each cluster node to store data -->
                    <max-size policy="USED_HEAP_SIZE">2048</max-size>
                    <!-- Evict the least frequently used entries first if we run out of space -->
                    <eviction-policy>LFU</eviction-policy>
                  </map>
                </hazelcast>
